//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2.FUJI.Napoleon.AccesoDatos.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class NAPOLEONEntities : DbContext
    {
        public NAPOLEONEntities()
            : base("name=NAPOLEONEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_CAT_Estatus> tbl_CAT_Estatus { get; set; }
        public DbSet<tbl_CAT_Modalidad> tbl_CAT_Modalidad { get; set; }
        public DbSet<tbl_CAT_Proyecto> tbl_CAT_Proyecto { get; set; }
        public DbSet<tbl_CAT_TipoUsuario> tbl_CAT_TipoUsuario { get; set; }
        public DbSet<tbl_CAT_Usuarios> tbl_CAT_Usuarios { get; set; }
        public DbSet<tbl_ConfigSitio> tbl_ConfigSitio { get; set; }
        public DbSet<tbl_DET_Estudio> tbl_DET_Estudio { get; set; }
        public DbSet<tbl_DET_Estudio_AUD> tbl_DET_Estudio_AUD { get; set; }
        public DbSet<tbl_MST_Estudio> tbl_MST_Estudio { get; set; }
        public DbSet<tbl_MST_PrioridadEstudio> tbl_MST_PrioridadEstudio { get; set; }
        public DbSet<tbl_REL_ProyectoSitio> tbl_REL_ProyectoSitio { get; set; }
        public DbSet<tbl_REL_SitioModalidad> tbl_REL_SitioModalidad { get; set; }
        public DbSet<tbl_ConfigSitio_AUD> tbl_ConfigSitio_AUD { get; set; }
        public DbSet<tbl_DET_ServicioSitio> tbl_DET_ServicioSitio { get; set; }
        public DbSet<tbl_RegistroSitio> tbl_RegistroSitio { get; set; }
    
        public virtual ObjectResult<stp_getEstudio_Result> stp_getEstudio(Nullable<int> intEstatusID, Nullable<int> id_Sitio, Nullable<int> intModalidadID)
        {
            var intEstatusIDParameter = intEstatusID.HasValue ?
                new ObjectParameter("intEstatusID", intEstatusID) :
                new ObjectParameter("intEstatusID", typeof(int));
    
            var id_SitioParameter = id_Sitio.HasValue ?
                new ObjectParameter("id_Sitio", id_Sitio) :
                new ObjectParameter("id_Sitio", typeof(int));
    
            var intModalidadIDParameter = intModalidadID.HasValue ?
                new ObjectParameter("intModalidadID", intModalidadID) :
                new ObjectParameter("intModalidadID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<stp_getEstudio_Result>("stp_getEstudio", intEstatusIDParameter, id_SitioParameter, intModalidadIDParameter);
        }
    }
}
