//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2.FUJI.Napoleon.AccesoDatos.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CAT_Estatus
    {
        public tbl_CAT_Estatus()
        {
            this.tbl_DET_Estudio = new HashSet<tbl_DET_Estudio>();
        }
    
        public int intEstatusID { get; set; }
        public string vchEstatusDesc { get; set; }
        public string vchClaveEstatus { get; set; }
        public Nullable<System.DateTime> datFecha { get; set; }
        public Nullable<bool> bitActivo { get; set; }
    
        public virtual ICollection<tbl_DET_Estudio> tbl_DET_Estudio { get; set; }
    }
}
